[phases.setup]
nixFile = ".nixpacks/config.nix"
aptPkgs = ["openssl", "postgresql-client"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start" 